autobuild-run: disable gdb & conntrack-tools for non-working toolchains
This MIPS uClibc toolchain doesn't have the needed fix in order to build
gdb and conntrack-tools packages statically for uClibc. It fails with
messages like these ones:

libdl.c:(.text+0x1840): undefined reference to `TLS_DTPREL_VALUE'
libdl.c:(.text+0x1884): undefined reference to `TLS_TPREL_VALUE'

This is due to certain missing fixes in uClibc, as built by
Crosstool-NG.

Related:
  http://lists.uclibc.org/pipermail/uclibc/2013-April/047708.html
  http://git.buildroot.net/buildroot/commit/?id=c0b4c45780e4ffe23101a407e7c4cde22e27815a

Fixes:
  http://autobuild.buildroot.net/results/77e/77e5f95ec4f0b3284eb7a48b8152690f8bf81a2a/
  http://autobuild.buildroot.net/results/977/977d901c500074a6b26f331ae43808bafab58239/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>