autobuild-run: Do not build python3 with this external toolchain
It fails to build python3 with an error like this one:

Failed to build these modules:
_posixsubprocess

Which comes from this previous error:

/br/output/build/python3-3.4.1/Modules/_posixsubprocess.c:246:33: error:
'SYS_getdents64' undeclared (first use in this function)

The failure is caused because this toolchain uses eglibc-2.18 which
lacks the definition of the SYS_getdents64 macro for MIPS64 n64.

Fixes:
	http://autobuild.buildroot.net/results/8fd/8fd1fdf5f02365278a280d50adce98303fcc9a2a/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>