autobuild-run: fix undefined log variable error in is_toolchain_usable()
The log variable from the is_toolchain_usable() function is not
defined, which causes an error when this function is executed:

  log_write(log, "WARN: ignoring the Linaro ARM toolchains becausee too old host glibc")
  NameError: global name 'log' is not defined

Fix this by fetching the log value from kwargs, as is done in other
functions.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>