autobuild-run: Do not build civetweb with a known non-working external MIPS toolchain
This MIPS uClibc toolchain doesn't have the needed fix in order to build
the civetweb package statically for uClibc. It fails with messages like
these ones:

libdl.c:(.text+0x1840): undefined reference to `TLS_DTPREL_VALUE'
libdl.c:(.text+0x1884): undefined reference to `TLS_TPREL_VALUE'

This is due to certain missing fixes in uClibc, as built by
Crosstool-NG.

Related:
  http://lists.uclibc.org/pipermail/uclibc/2013-April/047708.html
  http://git.buildroot.net/buildroot/commit/?id=c0b4c45780e4ffe23101a407e7c4cde22e27815a

Fixes:
  http://autobuild.buildroot.net/results/4a1/4a179bebdc9cd85780d7f16f672ee019a1947147/

[Thomas: adjust commit log.]

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>