autobuild-run: fix exception in execve() on Python 2.7
Peter Korsgaard reports:

 hmm, after updating my autobuilder instances saturday they all fail with python errors
 Traceback (most recent call last):
   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
     self.run()
   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
     self._target(*self._args, **self._kwargs)
   File "/home/peko/buildroot-test/scripts/autobuild-run", line 784, in run_instance
     ret = do_build(**kwargs)
   File "/home/peko/buildroot-test/scripts/autobuild-run", line 592, in do_build
     sub = subprocess.Popen(cmd, stdout=f, stderr=f)
   File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
     errread, errwrite)
   File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
     raise child_exception
 TypeError: execv() arg 2 must contain only strings
 this is python 2.7.3. Any ideas?

This regression is caused by the newly added "nice" option, for which
the argument is passed as an integer to subprocess.Popen(). In order
to fix that, turn it explicitly into a string.

Reported-by: Peter Korsgaard <peter@korsgaard.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>