autobuild-run: do not build weston using an incompatible toolchain
This external MIPS toolchain uses an old version of uClibc which doesn't
include this patch:

  http://git.uclibc.org/uClibc/commit/libc/sysdeps/linux?id=3d1b82c7d9dce11c733fe23a85df7f975c7e2486

Because of that, weston package fails to build with this error message:

src/compositor.c: In function
'weston_compositor_set_presentation_clock_software':
src/compositor.c:4283:3: error: 'CLOCK_MONOTONIC_RAW' undeclared (first
use in this function)
   CLOCK_MONOTONIC_RAW, /* no jumps, no crawling */

Fixes:

  http://autobuild.buildroot.net/results/d36/d367eda8b549b6facd624d0b44cfdc6eb0486c72/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>