autobuild-run: do not build strongswan using an incompatible toolchain
This external MIPS toolchain uses eglibc-2.18 which lacks the definition
of the SYS_getdents64 macro for MIPS64 n64. Because of that, strongswan
package fails to build and shows this error message:

utils/utils.c: In function 'closefrom':
utils/utils.c:151:25: error: 'SYS_getdents64' undeclared (first use in
this function)
   while ((len = syscall(SYS_getdents64, dir_fd, buffer,

Fixes:

  http://autobuild.buildroot.net/results/ea2/ea2be188b88ceb1cad4314bdaf00184cb74b9e26/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>